name: Elixir Phoenix CI

on:
  push:
    branches: '**'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    name: Mix tests
    runs-on: ubuntu-latest

    # ---------- Postgres service ----------
    services:
      db:
        image: postgres:15
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: qart_test
        options: >-
          --health-cmd "pg_isready -U postgres -d qart_test"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    # ---------- Job-wide env ----------
    env:
      MIX_ENV: test
      # Ecto can consume DATABASE_URL directly; hostname = 'db'
      DATABASE_URL: ecto://postgres:postgres@db:5432/qart_test
      PGHOST: db
      PGPASSWORD: postgres
      PGUSER: postgres
      BSV_NETWORK: ${{ secrets.BSV_NETWORK }}
      HANDCASH_API_KEY: ${{ secrets.HANDCASH_API_KEY }}
      HANDCASH_API_SECRET: ${{ secrets.HANDCASH_API_SECRET }}
      TEST_12_WORDS: ${{ secrets.TEST_12_WORDS }}
      VAULT_KEY: ${{ secrets.VAULT_KEY }}

    steps:
      - uses: actions/checkout@v4

      # ------- Install Elixir & OTP -------
      - name: Set up BEAM toolchain
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15.2'
          otp-version: '26.0'

      # ------- Restore caches -------
      - name: Cache Mix deps
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Cache _build
        uses: actions/cache@v3
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: ${{ runner.os }}-build-

      # ------- Install deps & compile -------
      - name: Install dependencies
        run: mix deps.get

      - name: Compile (warnings = errors)
        # run: mix compile --warnings-as-errors
        run: mix compile

      # ------- Prepare DB & run tests -------
      - name: Prepare database
        run: |
          mix ecto.create
          mix ecto.migrate

      - name: Run tests
        run: mix test --color
